version: '3.9'
services:
  dev:
    container_name: polyms-buster
    image: docker.pkg.github.com/polyms/devcontainers/buster:latest
    user: vscode
    working_dir: /workspaces
    restart: unless-stopped
    volumes:
      - ~/.ssh:/home/vscode/.ssh:cached

volumes:
  workspaces:
    external: true
